Dependency update 1
RegularExpressionKft/alien-invasion pull request #8
Opened 2019-09-10 09:49 UTC by SaturnV

2019-09-10 11:27 UTC, tasika16 reviewed
A package-lock.json-t felszoktuk commitolni?

2019-09-10 12:45 UTC, SaturnV commented
> A package-lock.json-t felszoktuk commitolni?

A TGben még nem, de kéne. Majd annak is eljön az ideje.

2019-09-10 13:25 UTC, takacsv requested changes

2019-09-10 13:25 UTC, takacsv commented on plugins/ws-server.coffee
> +      noServer: true
Felmehet az előző sor végére.

2019-09-10 13:25 UTC, takacsv commented on plugins/ws-server.coffee
>      @wss.on 'connection', @onServerConnection
Szerintem az on chainelhető, lehet hogy egy ügyes zárójellel az előző sorral már kezdődhet a chain.

2019-09-10 13:25 UTC, takacsv commented on plugins/ws-server.coffee
> +  onRouterDefault: (connection) =>
Szimplanyíl.

2019-09-11 13:30 UTC, SaturnV commented on plugins/ws-server.coffee
> +      noServer: true
done

2019-09-11 13:30 UTC, SaturnV commented on plugins/ws-server.coffee
>      @wss.on 'connection', @onServerConnection
done

2019-09-11 13:34 UTC, SaturnV commented on plugins/ws-server.coffee
> +  onRouterDefault: (connection) =>
done

2019-09-24 14:12 UTC, merged